# Generated by Django 4.2.2 on 2023-06-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_variação'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variação',
            new_name='Variacao',
        ),
    ]
