# Generated by Django 4.2.2 on 2023-06-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_variação_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
